development:
  database: coesapp_production
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: admin
  password: DB1d10m45#
  socket: /tmp/mysql.sock

production:

  database: coesapp_development
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: d15573230
  socket: /tmp/mysql.sock
